### ISSUE TITLE
Startup issues with PX4

### ISSUE THREAD

**Issue by ltf1001** [Poaos/LAEA#1]
Thank you to the author for sharing such an outstanding project. I have successfully installed all the necessary steps on Ubuntu 20.04 as instructed, and everything can be installed normally. However, when I tried to start the simulation environment according to the first step, I encountered the following error:
~/LAEA$ roslaunch px4_gazebo laea_gazebo_lidar.launch
... logging to /home/oem/.ros/log/5129359e-f4d6-11ee-9ee3-df354fbd0633/roslaunch-dell-3772081.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Resource not found: The following package was not found in <arg name="world" default="$(find mavlink_sitl_gazebo)/worlds/indoor_01.world"/>: mavlink_sitl_gazebo
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/oem/LAEA/src
ROS path [2]=/opt/ros/noetic/share
The traceback for the exception was written to the log file
How to resolve this error?

**Comment by Poaos** [comment]
Thanks for trying our work, but as mentioned in the readme, we need to use the **default PX4 simulation environment** to **provide the required data topics** for the algorithms, containing data from the **depth camera, LIDAR**, etc. (Of course, other simulation environments are possible, just with some modifications, which are also mentioned in the readme). 
For your case, you need to **additionally configure the px4 gazebo simulation environment** and **copy the simulation model files provided** by the algorithm to your simulation environment folder (The drone model files and world files required for the px4 simulation are located in the px4_gazebo/resource).  
You can refer to the **px4 official tutorial for px4 simulation environment configuration**, the process of encountering problems can google or bing. Some links to configure the environment are as follows：
px4 official tutorial: https://docs.px4.io/main/en/dev_setup/dev_env_linux_ubuntu.html 
csdn from mainland China: https://blog.csdn.net/weixin_45291614/article/details/133657158
