### ISSUE TITLE
[ WARN] [1720103255.728859210, 14937.430000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame world (parent map) at time 14937.460000 according to authority unknown_publisher

### ISSUE THREAD

**Issue by Yangye0526** [Poaos/LAEA#2]
[ WARN] [1720103255.728859210, 14937.430000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame world (parent map) at time 14937.460000 according to authority unknown_publisher 一启动explore_test.launch就会报这个错，建图看着好像没啥问题
![2fad2e74-709b-4a13-8215-4e33d6dba181](https://github.com/Poaos/LAEA/assets/110235486/1e7d1364-6e4b-447c-97b1-6027589f3ce1)
![402c614e-29c9-4d78-b52b-2c4d2a4db9d8](https://github.com/Poaos/LAEA/assets/110235486/2d53da4c-f684-4994-939e-fa2027aa51e0)
一直不动，请问是什么问题呢

**Comment by Poaos** [comment]
TF_REPEATED_DATA的问题可以`rosrun rqt_tf_tree rqt_tf_tree `查看一下系统里面的tf树是不是没有正常连接上（检查启动的系列程序是否存在tf关系发布的报错），这个报错有时候可以忽略。 这套算法需要使用**mavros_controller**接收探索算法的轨迹并解算无人机的控制量，**走的mavros通信**，所以需要**手动切入offboard并解锁**。该操作可以在qgc里面操作，也可以使用命令行指令。

> [ WARN] [1720103255.728859210, 14937.430000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame world (parent map) at time 14937.460000 according to authority unknown_publisher 一启动explore_test.launch就会报这个错，建图看着好像没啥问题 ![2fad2e74-709b-4a13-8215-4e33d6dba181](https://private-user-images.githubusercontent.com/110235486/345868028-1e7d1364-6e4b-447c-97b1-6027589f3ce1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMTY5OTAsIm5iZiI6MTcyMDMxNjY5MCwicGF0aCI6Ii8xMTAyMzU0ODYvMzQ1ODY4MDI4LTFlN2QxMzY0LTZlNGItNDQ3Yy05N2IxLTYwMjc1ODlmM2NlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwMTQ0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjcwNGYyZTlhYWFiNTkxMjU4ZGQyNzE5MzU0OTUxZTZhZjlhZGQ0M2FmNDJiYjhlOWE5ZmYzZDFkNzVmYjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q-ClpN3zWo5SLu_CJ_S272kITb7uAKeme01mQwVPnTE) ![402c614e-29c9-4d78-b52b-2c4d2a4db9d8](https://private-user-images.githubusercontent.com/110235486/345868045-2d53da4c-f684-4994-939e-fa2027aa51e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMTY5OTAsIm5iZiI6MTcyMDMxNjY5MCwicGF0aCI6Ii8xMTAyMzU0ODYvMzQ1ODY4MDQ1LTJkNTNkYTRjLWY2ODQtNDk5NC05MzllLWZhMjAyN2FhNTFlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwMTQ0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2QzMTQ5NDQ3M2Q4NGIxM2IzMDBmYzYxNjU1YjI1M2E2Y2ZiODVhZDM5OGQxNzFlMzc4ZGZjZDFiOTRkOWM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.96OeQSpCGA2NQRM921SO0OIqAmsHLcXiuzlNXqtFurg) 一直不动，请问是什么问题呢

TF_REPEATED_DATA的问题可以`rosrun rqt_tf_tree rqt_tf_tree `查看一下系统里面的tf树是不是没有正常连接上（检查启动的系列程序是否存在tf关系发布的报错），这个报错有时候可以忽略（pkill -f roscore* ， roscore&，然后重新启动相关程序**可能**就好了）。 这套算法需要使用**mavros_controller**接收探索算法的轨迹并解算无人机的控制量，**走的mavros通信**，所以需要**手动切入offboard并解锁**。该操作可以在qgc里面操作，也可以使用命令行指令。
```bash
# 查看 tf 树发布情况，是否连接正常
rosrun rqt_tf_tree rqt_tf_tree

# 杀掉所有roscore程序，把环境弄干净点
# pkill -f roscore*
# 后台启动roscore，保障程序之间的正常通信
# roscore&

# In another terminal  手动切入offboard并解
rosrun mavros mavsys mode -c OFFBOARD
rosrun mavros mavsafety arm
```

**Comment by Yangye0526** [comment]
我发现我在运行的过程中经常出现#1    Object "/home/yy/exploration_demo/laea_ws/devel/lib/libactive_perception.so", at 0x7f15298f7802, in fast_planner::FrontierFinder::count_Lidar_VisibleCells(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, double const&, std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > > const&, int&, Eigen::Matrix<double, 3, 1, 0, 3, 1>&)
#0    Object "/home/yy/exploration_demo/laea_ws/devel/lib/libactive_perception.so", at 0x7f152991709e, in Lidar_gain::Get_Multi_Raycast(std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >, std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >, std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >&)
Segmentation fault (Address not mapped to object [(nil)])
[exploration_node-2] process has died [pid 1888891, exit code -11, cmd /home/yy/exploration_demo/laea_ws/devel/lib/exploration_manager/exploration_node /odom_world:=/mavros/local_position/odom /map_ros/pose:=/camera_pose /map_ros/depth:=/camera/depth/image_raw /map_ros/cloud:=/pcl_render_node/cloud /planning/pos_cmd:=position_cmd /projected_map:=/sdf_map/hybrid_2d /planning/travel_traj:=/planning/travel_traj_ours __name:=exploration_node __log:=/home/yy/.ros/log/599e2598-3c22-11ef-ac25-f1155abdff5a/exploration_node-2.log].
log file: /home/yy/.ros/log/599e2598-3c22-11ef-ac25-f1155abdff5a/exploration_node-2*.log
这个报错，不知道问题在哪，运行成功一次但是一直在一个地方打转了
![2321744DFC2B172B1E94105227A9A5ED](https://github.com/Poaos/LAEA/assets/110235486/eb33d27a-c090-479b-8050-8657d98f3554)
![64A8D3FA1D55032A09E81CDC9BD10391](https://github.com/Poaos/LAEA/assets/110235486/05cdfea0-e0b4-4628-8f8f-19b13381a737)

**Comment by Poaos** [comment]
> 我发现我在运行的过程中经常出现#1 Object "/home/yy/exploration_demo/laea_ws/devel/lib/libactive_perception.so", at 0x7f15298f7802, in fast_planner::FrontierFinder::count_Lidar_VisibleCells(Eigen::Matrix<double, 3, 1, 0, 3, 1> const&, double const&, std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > > const&, int&, Eigen::Matrix<double, 3, 1, 0, 3, 1>&) #0 Object "/home/yy/exploration_demo/laea_ws/devel/lib/libactive_perception.so", at 0x7f152991709e, in Lidar_gain::Get_Multi_Raycast(std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >, std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >, std::vector<Eigen::Matrix<double, 3, 1, 0, 3, 1>, std::allocator<Eigen::Matrix<double, 3, 1, 0, 3, 1> > >&) Segmentation fault (Address not mapped to object [(nil)]) [exploration_node-2] process has died [pid 1888891, exit code -11, cmd /home/yy/exploration_demo/laea_ws/devel/lib/exploration_manager/exploration_node /odom_world:=/mavros/local_position/odom /map_ros/pose:=/camera_pose /map_ros/depth:=/camera/depth/image_raw /map_ros/cloud:=/pcl_render_node/cloud /planning/pos_cmd:=position_cmd /projected_map:=/sdf_map/hybrid_2d /planning/travel_traj:=/planning/travel_traj_ours __name:=exploration_node __log:=/home/yy/.ros/log/599e2598-3c22-11ef-ac25-f1155abdff5a/exploration_node-2.log]. log file: /home/yy/.ros/log/599e2598-3c22-11ef-ac25-f1155abdff5a/exploration_node-2*.log 这个报错，不知道问题在哪，运行成功一次但是一直在一个地方打转了 ![2321744DFC2B172B1E94105227A9A5ED](https://private-user-images.githubusercontent.com/110235486/346315509-eb33d27a-c090-479b-8050-8657d98f3554.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjQ0NzYsIm5iZiI6MTcyMDM2NDE3NiwicGF0aCI6Ii8xMTAyMzU0ODYvMzQ2MzE1NTA5LWViMzNkMjdhLWMwOTAtNDc5Yi04MDUwLTg2NTdkOThmMzU1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QxNDU2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzVmNGNkYWQxODQxZTRmMmRjMDRhYzIyNjE0ZjBlZDRjM2I3YWI4NzU1NjUyODliOWIzMjFmNTA0NTE4ZmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wt0LO-r6Kan2RT24GoIkbhgSt28qe_ujZWx_fsLU0ZE) ![64A8D3FA1D55032A09E81CDC9BD10391](https://private-user-images.githubusercontent.com/110235486/346315513-05cdfea0-e0b4-4628-8f8f-19b13381a737.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjQ0NzYsIm5iZiI6MTcyMDM2NDE3NiwicGF0aCI6Ii8xMTAyMzU0ODYvMzQ2MzE1NTEzLTA1Y2RmZWEwLWUwYjQtNDYyOC04ZjhmLTE5YjEzMzgxYTczNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QxNDU2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzY1YmY3NWM5NjZkNzI5ODA2NTNjZDQzYWY1MGUzMzVlNDRiMjM3NGU0YzdjZTkxNGU5NTZhNmZjZmQwNzgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mrcvXNGjNMn5g2avUg3UlGledABZch9YAAS00ptKVkw)

这个报错应该和内存分配有关系，**可能是内存不够炸了**。目前这套算法是基于FAEP->FUEL的框架修改的，程序本身存在一定的bug，我之前在自己的笔记本上面运行偶尔也会出现类似问题，不过主要是在调用`getFullCostMatrix()`函数的时候。你这里在调用`Get_Multi_Raycast`的时候报错我还真没怎么遇到过，我在Ubuntu18和20下基本上是正常运行的，笔记本i5-12500h, **16g内存**。

**Comment by hosonhere** [comment]
我也有遇到类似的问题.
我发现`Lidar_gain::Get_Multi_Raycast`中有呼叫到的`Lidar_gain::getOccupancy(const Eigen::Vector3i& id)`中, 执行时计算出的idex可能会有问题.

后来我再下面加上
`if (idex < 0 || idex >= OccGrid.data.size()) return -1;`
就正常了
