### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by hosonhere** [Poaos/LAEA#3]
在运行`fast_planner::MapROS::init()`的时候出现了Segmentation fault.

Enviroment: Ubuntu 20.04 + ROS noetic
报错:
PARAMETERS
 * /exploration_node/astar/allocate_num: 1000000
 * /exploration_node/astar/lambda_heu: 10000.0
 * /exploration_node/astar/max_search_time: 0.001
 * /exploration_node/astar/resolution_astar: 0.2
 * /exploration_node/bspline/limit_acc: 1.0
 * /exploration_node/bspline/limit_ratio: 1.1
 * /exploration_node/bspline/limit_vel: 1.0
 * /exploration_node/exploration/am: 1.0
 * /exploration_node/exploration/lens_lb_rate: 1.35
 * /exploration_node/exploration/max_decay: 0.8
 * /exploration_node/exploration/max_yaw_gap: 100
 * /exploration_node/exploration/refine_local: True
 * /exploration_node/exploration/refined_num: 7
 * /exploration_node/exploration/refined_radius: 5.0
 * /exploration_node/exploration/relax_time: 1.0
 * /exploration_node/exploration/temp_next_yaw_thresh: 2.5
 * /exploration_node/exploration/top_view_num: 15
 * /exploration_node/exploration/tsp_dir: /home/hoson/laea_...
 * /exploration_node/exploration/vm: 1.0
 * /exploration_node/exploration/w_dir: 1.5
 * /exploration_node/exploration/yaw_rotate_rate: 1.2
 * /exploration_node/exploration/yd: 1.3089969166666668
 * /exploration_node/exploration/ydd: 1.5707963
 * /exploration_node/frontier/candidate_dphi: 0.2617993833333333
 * /exploration_node/frontier/candidate_rmax: 2.5
 * /exploration_node/frontier/candidate_rmin: 1.5
 * /exploration_node/frontier/candidate_rnum: 3
 * /exploration_node/frontier/cluster_min: 12
 * /exploration_node/frontier/cluster_size_xy: 2.0
 * /exploration_node/frontier/cluster_size_z: 10.0
 * /exploration_node/frontier/down_sample: 3
 * /exploration_node/frontier/enable_boundary_cost: True
 * /exploration_node/frontier/isolateArea_gain: 15.0
 * /exploration_node/frontier/min_candidate_clearance: 0.21
 * /exploration_node/frontier/min_candidate_dist: 0.75
 * /exploration_node/frontier/min_view_finish_fraction: 0.2
 * /exploration_node/frontier/min_visib_num: 12
 * /exploration_node/frontier/small_area_thresh: 2.0
 * /exploration_node/frontier/small_thresh_low: 0.6
 * /exploration_node/frontier/use_hybird_map: True
 * /exploration_node/frontier/w_angleRate: 0.05
 * /exploration_node/frontier/w_edgeRate: 1.1
 * /exploration_node/frontier/w_isoareaRate: 1.2
 * /exploration_node/frontier/w_smallareaRate: 1.0
 * /exploration_node/frontier/x_bound_max: 23.0
 * /exploration_node/frontier/x_bound_min: -23.0
 * /exploration_node/frontier/y_bound_max: 11.0
 * /exploration_node/frontier/y_bound_min: -11.0
 * /exploration_node/fsm/enable_yawing: False
 * /exploration_node/fsm/init_x: 0.0
 * /exploration_node/fsm/init_y: 0.0
 * /exploration_node/fsm/init_z: 1.0
 * /exploration_node/fsm/replan_time: 0.2
 * /exploration_node/fsm/thresh_replan1: 0.5
 * /exploration_node/fsm/thresh_replan2: 0.5
 * /exploration_node/fsm/thresh_replan3: 1.5
 * /exploration_node/heading_planner/half_vert_num: 5
 * /exploration_node/heading_planner/lambda1: 2.0
 * /exploration_node/heading_planner/lambda2: 1.0
 * /exploration_node/heading_planner/max_yaw_rate: 0.17453292222222222
 * /exploration_node/heading_planner/w: 20000.0
 * /exploration_node/heading_planner/weight_type: 1.0
 * /exploration_node/heading_planner/yaw_diff: 0.5235987666666666
 * /exploration_node/manager/clearance_threshold: 0.2
 * /exploration_node/manager/control_points_distance: 0.5
 * /exploration_node/manager/dynamic_environment: 0
 * /exploration_node/manager/local_segment_length: 6.0
 * /exploration_node/manager/max_acc: 1.0
 * /exploration_node/manager/max_jerk: 4.0
 * /exploration_node/manager/max_vel: 1.0
 * /exploration_node/manager/min_time: True
 * /exploration_node/manager/use_active_perception: True
 * /exploration_node/manager/use_geometric_path: True
 * /exploration_node/manager/use_kinodynamic_path: True
 * /exploration_node/manager/use_optimization: True
 * /exploration_node/manager/use_topo_path: True
 * /exploration_node/map_ros/bounding_big: 2500
 * /exploration_node/map_ros/bounding_small: 3
 * /exploration_node/map_ros/contours_thesh_: 100
 * /exploration_node/map_ros/cx: 321.04638671875
 * /exploration_node/map_ros/cy: 243.44969177246094
 * /exploration_node/map_ros/depth_filter_margin: 2
 * /exploration_node/map_ros/depth_filter_maxdist: 5.0
 * /exploration_node/map_ros/depth_filter_mindist: 0.2
 * /exploration_node/map_ros/downsample_2d_resolution: 0.15
 * /exploration_node/map_ros/esdf_slice_height: 0.3
 * /exploration_node/map_ros/frame_id: world
 * /exploration_node/map_ros/fx: 387.229248046875
 * /exploration_node/map_ros/fy: 387.229248046875
 * /exploration_node/map_ros/k_depth_scaling_factor: 1000.0
 * /exploration_node/map_ros/pub_bbox_marker: False
 * /exploration_node/map_ros/pub_downsample_2d: False
 * /exploration_node/map_ros/pub_normal_2d: False
 * /exploration_node/map_ros/qw: 0
 * /exploration_node/map_ros/qx: 0.707
 * /exploration_node/map_ros/qy: 0.707
 * /exploration_node/map_ros/qz: 0
 * /exploration_node/map_ros/show_all_map: True
 * /exploration_node/map_ros/show_esdf_time: False
 * /exploration_node/map_ros/show_occ_time: False
 * /exploration_node/map_ros/skip_pixel: 2
 * /exploration_node/map_ros/use_hybird_map: True
 * /exploration_node/map_ros/use_new_thread: False
 * /exploration_node/map_ros/visualization_truncate_height: 10.09
 * /exploration_node/map_ros/visualization_truncate_low: -2.0
 * /exploration_node/optimization/algorithm1: 15
 * /exploration_node/optimization/algorithm2: 11
 * /exploration_node/optimization/dist0: 0.7
 * /exploration_node/optimization/ld_dist: 10.0
 * /exploration_node/optimization/ld_end: 0.7
 * /exploration_node/optimization/ld_feasi: 2.0
 * /exploration_node/optimization/ld_guide: 1.5
 * /exploration_node/optimization/ld_smooth: 20.0
 * /exploration_node/optimization/ld_start: 100.0
 * /exploration_node/optimization/ld_time: 1.0
 * /exploration_node/optimization/ld_view: 0.0
 * /exploration_node/optimization/ld_waypt: 0.3
 * /exploration_node/optimization/max_acc: 1.0
 * /exploration_node/optimization/max_ddyaw: 6.2831852
 * /exploration_node/optimization/max_dyaw: 1.0471975333333332
 * /exploration_node/optimization/max_iteration_num1: 2
 * /exploration_node/optimization/max_iteration_num2: 2000
 * /exploration_node/optimization/max_iteration_num3: 200
 * /exploration_node/optimization/max_iteration_num4: 200
 * /exploration_node/optimization/max_iteration_time1: 0.0001
 * /exploration_node/optimization/max_iteration_time2: 0.005
 * /exploration_node/optimization/max_iteration_time3: 0.003
 * /exploration_node/optimization/max_iteration_time4: 0.003
 * /exploration_node/optimization/max_vel: 1.0
 * /exploration_node/perception_utils/left_angle: 0.69222
 * /exploration_node/perception_utils/max_dist: 4.5
 * /exploration_node/perception_utils/right_angle: 0.68901
 * /exploration_node/perception_utils/top_angle: 0.56125
 * /exploration_node/perception_utils/vis_dist: 1.0
 * /exploration_node/sdf_map/box_max_x: 23.0
 * /exploration_node/sdf_map/box_max_y: 11.0
 * /exploration_node/sdf_map/box_max_z: 2.3
 * /exploration_node/sdf_map/box_min_x: -23.0
 * /exploration_node/sdf_map/box_min_y: -11.0
 * /exploration_node/sdf_map/box_min_z: -0.1
 * /exploration_node/sdf_map/default_dist: 0.0
 * /exploration_node/sdf_map/ground_height: -0.1
 * /exploration_node/sdf_map/local_bound_inflate: 0.5
 * /exploration_node/sdf_map/local_map_margin: 50
 * /exploration_node/sdf_map/map_size_x: 80.0
 * /exploration_node/sdf_map/map_size_y: 80.0
 * /exploration_node/sdf_map/map_size_z: 3.0
 * /exploration_node/sdf_map/max_ray_length: 4.5
 * /exploration_node/sdf_map/min_ray_length: 0.5
 * /exploration_node/sdf_map/obstacles_inflation: 0.45
 * /exploration_node/sdf_map/optimistic: False
 * /exploration_node/sdf_map/p_hit: 0.65
 * /exploration_node/sdf_map/p_max: 0.9
 * /exploration_node/sdf_map/p_min: 0.12
 * /exploration_node/sdf_map/p_miss: 0.35
 * /exploration_node/sdf_map/p_occ: 0.8
 * /exploration_node/sdf_map/resolution: 0.12
 * /exploration_node/sdf_map/signed_dist: False
 * /exploration_node/sdf_map/virtual_ceil_height: -10
 * /exploration_node/search/allocate_num: 100000
 * /exploration_node/search/check_num: 10
 * /exploration_node/search/horizon: 5.0
 * /exploration_node/search/init_max_tau: 1.0
 * /exploration_node/search/lambda_heu: 10.0
 * /exploration_node/search/margin: 0.2
 * /exploration_node/search/max_acc: 1.0
 * /exploration_node/search/max_tau: 0.8
 * /exploration_node/search/max_vel: 1.0
 * /exploration_node/search/optimistic: False
 * /exploration_node/search/resolution_astar: 0.025
 * /exploration_node/search/time_resolution: 0.8
 * /exploration_node/search/vel_margin: 0.25
 * /exploration_node/search/w_time: 10.0
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /waypoint_generator/waypoint_type: point

NODES
  /
    exploration_node (exploration_manager/exploration_node)
    tf_map2world_link (tf/static_transform_publisher)
    waypoint_generator (waypoint_generator/waypoint_generator)

ROS_MASTER_URI=http://localhost:11311

process[tf_map2world_link-1]: started with pid [59897]
process[exploration_node-2]: started with pid [59898]
process[waypoint_generator-3]: started with pid [59899]
hit: 0.619039, miss: -0.619039, min: -1.99243, max: 2.19722, thresh: 1.38629
[ INFO] [1721039240.335375276]: Successfully loaded the parameters from the launch file
Stack trace (most recent call last):
#8    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#7    Object "/home/hoson/laea_ws/devel/lib/exploration_manager/exploration_node", at 0x55711c76d3ed, in _start
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f5707ae7082, in __libc_start_main
#5    Object "/home/hoson/laea_ws/devel/lib/exploration_manager/exploration_node", at 0x55711c76d08f, in main
#4    Object "/home/hoson/laea_ws/devel/lib/exploration_manager/exploration_node", at 0x55711c77ae81, in fast_planner::FastExplorationFSM::init(ros::NodeHandle&)
#3    Object "/home/hoson/laea_ws/devel/lib/exploration_manager/exploration_node", at 0x55711c78c7db, in fast_planner::FastExplorationManager::initialize(ros::NodeHandle&)
#2    Object "/home/hoson/laea_ws/devel/lib/libplan_manage.so", at 0x7f570847d018, in fast_planner::FastPlannerManager::initPlanModules(ros::NodeHandle&)
#1    Object "/home/hoson/laea_ws/devel/lib/libplan_env.so", at 0x7f57083097cc, in fast_planner::SDFMap::initMap(ros::NodeHandle&)
#0    Object "/home/hoson/laea_ws/devel/lib/libplan_env.so", at 0x7f570832abb8, in fast_planner::MapROS::init()
Segmentation fault (Signal sent by the kernel [(nil)])
[exploration_node-2] process has died [pid 59898, exit code -11, cmd /home/hoson/laea_ws/devel/lib/exploration_manager/exploration_node /odom_world:=/mavros/local_position/odom /map_ros/pose:=/mavros/camera/pose /map_ros/depth:=/camera/depth/image_raw /map_ros/cloud:=/pcl_render_node/cloud /planning/pos_cmd:=position_cmd /projected_map:=/sdf_map/hybrid_2d /planning/travel_traj:=/planning/travel_traj_ours __name:=exploration_node __log:=/home/hoson/.ros/log/c78f4898-4294-11ef-b1ae-1b7232513940/exploration_node-2.log].
log file: /home/hoson/.ros/log/c78f4898-4294-11ef-b1ae-1b7232513940/exploration_node-2*.log

![image](https://github.com/user-attachments/assets/032d5068-b52e-47d4-a28c-113363c68c97)

**Comment by Poaos** [comment]
这个报错我确实是没有遇到过，请检查相关环境依赖和程序启动顺序。我在Ubuntu20 noetic下按流程启动没有遇到过这些报错。fast_planner::MapROS::init() 中本身也没有什么特别的操作，如果每次都是这个报错，不如手动**添加一些 std::cout 进行测试**，查看程序死在了哪个具体的位置，以便纠错。
![image](https://github.com/user-attachments/assets/52a1f3a4-e3b4-4aaf-9ce5-116b515338be)

**Comment by hosonhere** [comment]
谢谢您的回覆! 很不幸的, 根据我设定的std::cout, 他每次运行的时候**中断的位置**是不一致的, 我想可能是环境有问题, 我再重新装一次试试!

**Comment by hosonhere** [comment]
刚刚我改成用C++ 17编译成功debug
